name: Master workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup project
      run: make setup
      
    - name: Check lint
      run: make lint
      
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: make test
